services:
  - type: web
    name: telegram-signal-forwarder
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    plan: free
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: PHONE
        sync: false
      - key: SESSION_STRING
        sync: false
      - key: SOURCE_CHANNEL
        sync: false
      - key: TARGET_CHANNEL
        sync: false
      - key: PING_TOKEN
        sync: false
      - key: PORT
        value: 10000
      - key: DUPLICATE_WINDOW
        value: 5
