name: Keep Render App Awake

on:
  schedule:
    # Every 5 minutes
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render keepalive endpoint
        run: |
          echo "Pinging Render app..."
          curl -fsS -H "Authorization: Bearer ${{ secrets.RENDER_PING_TOKEN }}" \
            https://telegram-signal-forwarder.onrender.com/ping \
            || echo "Ping failed"
